defaults:
  - agent: ppo
  - agent/ppo/policy: xtma_beta
  - agent/ppo/training: ppo
  - agent/ppo/obs_configs: birdview
  - train_envs: standard
actors:
  hero:
    agent: ppo
    reward:
      entry_point: reward.valeo_action:ValeoAction
      kwargs: {}
    terminal:
      entry_point: terminal.valeo_no_det_px:ValeoNoDetPx
      kwargs: {}
ev_id: hero
carla_sh_path: /home/ubuntu/apps/carla/carla910/CarlaUE4.sh
total_timesteps: 1024 #1e8
seed: 2021
kill_running: true
dummy: true # true diyorum şimdi bakalım ne olacak
token : 3fe8df1737825eb3
wb_project: train_rl
wb_name: null
wb_notes: null
wb_tags: null
curriculum: false